### ISSUE TITLE
Is the input size of function "get_model_complexity_info()" must be fixed to 3 demensions?

### ISSUE THREAD

**Issue by Zhang-Lilai** [sovrasov/flops-counter.pytorch#102]
The function has no problem when the input is a 3D Tensor. 
However, when we enter a 4D Tensor,  this function will report a bug of " wrong dimension":
Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 3, 224, 1]
I am running a network whose input demension has to be fixed to 4.  
Is there any way to enable it to input different dimensions of Tensors?

**Comment by sovrasov** [comment]
Hi! See https://github.com/sovrasov/flops-counter.pytorch/issues/14

**Comment by Zhang-Lilai** [comment]
It works! Thank you very much for your help!



---Original---
From: "Vladislav ***@***.***&gt;
Date: Mon, Dec 12, 2022 18:53 PM
To: ***@***.***&gt;;
Cc: "Zhang ***@***.******@***.***&gt;;
Subject: Re: [sovrasov/flops-counter.pytorch] Is the input size of function"get_model_complexity_info()" must be fixed to 3 demensions? (Issue #102)




 
Hi! See #14
