### ISSUE TITLE
How do I calculate the FLOPs of a model with some frozen layers during training?

### ISSUE THREAD

**Issue by js-lee-AI** [sovrasov/flops-counter.pytorch#103]
Thank you so much for sharing the code.

As far as I know, frozen layers have no effect on FLOPs in the forward pass. That is, even if frozen layers are included, FLOPs is only affected by the total number of parameters.

So, how do estimate the FLOPs in the backward pass when there are some frozen layers im the model? Is it correct to simply calculate `2 * forward_FLOPs`?

I wonder if this code reflects my question.
If not, can someone please help me?

Thank you!

**Comment by sovrasov** [comment]
Frozen layers contribute to the total flops at forward, but their parameters are not included into the final params counter output.

ptflops is designed to evaluate computational complexity of pytorch models on inference stage. It doesn't have any functionality related to tracking the backward pass and I don't recommend use it for evaluating the training complexity, unless you have a deep understanding of pytorch mechanics and know what you are doing.
