### ISSUE TITLE
The Conv1d with the same architecture yields different Macs in different models

### ISSUE THREAD

**Issue by R7788380** [sovrasov/flops-counter.pytorch#111]
I calculated the Macs for the same Conv1d architecture with same input in different models, and normally I would expect to obtain the same Macs. Why am I getting different Macs?

Here are the results for the Conv1d in the first model:
Code:
```
with torch.cuda.device(0):
    macs, params = get_model_complexity_info(model, (2, 44100), as_strings=True, print_per_layer_stat=True, verbose=True)
    print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
    print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```
Result:
```
(0): HEncLayer(
      1.34 k, 0.066% Params, 128.62 MMac, 0.566% MACs, 
      (conv): Conv1d(272, 0.013% Params, 26.03 MMac, 0.114% MACs, 2, 16, kernel_size=(8,), stride=(4,), padding=(2,))
```

And here are the results after extracting the Conv1d from the first model and performing the calculation:
Code:
```
with torch.cuda.device(0):
    macs, params = get_model_complexity_info(model.tencoder[0].conv, (2, 44100), as_strings=True, print_per_layer_stat=True, verbose=True)
    print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
    print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```
Result:
```
Conv1d(272, 100.00% Params, 3.0 MMac, 100.000% MACs, 2, 16, kernel_size=(8,), stride=(4,), padding=(2,))
```

**Comment by sovrasov** [comment]
@R7788380 ptflops calculate the resulting flops of conv operation depending on the output tensor dimension. Could you provide input and output shapes for both cases?

**Comment by R7788380** [comment]
@sovrasov Thanks for your reply.

Here are the input and output shapes in first model:
```
tensor = torch.rand((1,2,44100)) # Input shape: (1,2,44100)
first_out = model(tensor)
first_out.shape  # Output shape: (1,5,2,44100)
```

Second model:
```
tensor = torch.rand((1,2,44100)) # Input shape: (1,2,44100)
sec_out = model.tencoder[0].conv(tensor)
sec_out.shape # Output shape: (1,16,11025)
```

The output of the first model is different from Conv1d due to the inclusion of additional modules such as Conv2d, GeLU, GroupNormalization, and so on. 
However, I can confirm that both the first and second models have a Conv1d input shape of (1, 2, 44100). The Conv1d layer in the first model directly receives the input shape (1, 2, 44100) without being affected by other layers.

**Comment by sovrasov** [comment]
Thanks for the update, but to identify the problem, I need the exact input / output shapes of the conv module.
The calculation hook relies on the kernel size and output tensor shape:
https://github.com/sovrasov/flops-counter.pytorch/blob/master/ptflops/pytorch_ops.py#LL70C31-L70C31

**Comment by R7788380** [comment]
I apologize for the confusion. After **carefully examining** both inputs and outputs, I realized that the first model's input was not processed correctly.

After proper processing, the Macs for both models are the same.
First: 
Code:
```
model.use_train_segment = False # Turn off the training mode
with torch.cuda.device(0):
    macs, params = get_model_complexity_info(model, (2, 44100), as_strings=True, print_per_layer_stat=True, verbose=True)
    print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
    print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```
Result:
```
(0): HEncLayer(
      1.34 k, 0.066% Params, 14.82 MMac, 0.814% MACs, 
      (conv): Conv1d(272, 0.013% Params, 3.0 MMac, 0.165% MACs, 2, 16, kernel_size=(8,), stride=(4,), padding=(2,))
```

You're very welcome! Thank you for your response.
