### ISSUE TITLE
Question : computing batch size in "conv_flops_counter_hook".

### ISSUE THREAD

**Issue by ehdrbs4935** [sovrasov/flops-counter.pytorch#138]
In the function of **"conv_flops_counter_hook"**,

```
def conv_flops_counter_hook(conv_module, input, output, extra_per_position_flops=0):
    # Can have multiple inputs, getting the first one
    input = input[0]

    batch_size = input.shape[0]
    output_dims = list(output.shape[2:])
```

The shape of input is torch.Size(['batch_size', 'number of channels', 'height', 'width']).
Through "input = input[0]", the size of 'input' variable updates to ['number of channels', 'height', 'width']. 
Then "input.shape[0]" returns 'number of channels' not batch_size.

Please explain what I don't understand.

**Comment by sovrasov** [comment]
Input here is a tuple of input tensors, therefore the hook picks up the first tensor, which is the conv argument. This argument has BCHW shape, as you mentioned.

**Comment by ehdrbs4935** [comment]
Oh thank you! I understand :)
