### ISSUE TITLE
 Does it support dilation convolution?

### ISSUE THREAD

**Issue by xxsgcjwddsg** [sovrasov/flops-counter.pytorch#15]

**Comment by sovrasov** [comment]
Yes, ptflops supports convolution kernels with dilations. It doesn't implicitly appear in code because counter relies on spatial resolution of output tensor.

**Comment by pgr2015** [comment]
@sovrasov Hi, could you please explain the dilation convolutional layer? It is clear that parameter amount stays same compared with standard conv, but what about flops? Will it increase or not?

**Comment by sovrasov** [comment]
Dilated convolution consumes almost the same amount of flops as a regular one in case if size of kernel is exactly the same. If padding is big enough dilated convolution will be able to apply it's kernel exactly the same amount of times as regular. Each computation of kernel costs equally for the both convolutions. This is true only for 'honest' implementation: dilated convolution also can be implemented using regular one with bigger kernel size. In this case amount of computations will be increased.
