### ISSUE TITLE
stride not considered in the conv_flops_counter_hook

### ISSUE THREAD

**Issue by yashbhalgat** [sovrasov/flops-counter.pytorch#19]
Hi @sovrasov ,
Why does the `conv_flops_counter_hook` not consider the stride of the convolutions? Can you please add support for that as it significantly affects the MAC count?

**Comment by sovrasov** [comment]
This hook takes into account spacial size of the output blob after convolution. In case of stride > 1 spacial size decreases sufficiently and thus the output number is correct.

**Comment by yashbhalgat** [comment]
That make sense, thanks for the explanation! :)
