### ISSUE TITLE
Error with flops_model.eval().start_flops_count()

### ISSUE THREAD

**Issue by Phoenix1327** [sovrasov/flops-counter.pytorch#20]
https://github.com/sovrasov/flops-counter.pytorch/blob/af0816f8a77c2ef542e05cdf4d6f9b8048156b2a/ptflops/flops_counter.py#L15
My pytorch version is 1.1.0 and I try to calculate the flops for my own designed model.
But there exists errors in line 15, since `flops_model.eval()` will return `NoneType` object.

Until I decompose the line 15 into:
`flops_model.eval()`
`flops_model.start_flops_count()`
the program processes properly.

**Comment by sovrasov** [comment]
Strange error. Nobody had it before. Do you have overrided eval() in your custom model?

**Comment by Phoenix1327** [comment]
> Strange error. Nobody had it before. Do you have overrided eval() in your custom model?

No, and I suppose the error has nothing with pytorch version, since the standard model imported from torchvision works properly.
