### ISSUE TITLE
Error when loading from a saved checkpoint file

### ISSUE THREAD

**Issue by PlumedSerpent** [sovrasov/flops-counter.pytorch#25]
Hi, I have a training script with structure as :
model=Net()
flops, params = get_model_complexity_info(model, (3, 256, 256), as_strings=True, print_per_layer_stat=True)
print('Flops:  ' + flops)
print('Params: ' + params)
training
torch.save(model)
Then when I tried to load from above saved checkpoint using torch.load('checkpoint.pth'), it occurs into an error:
AttributeError: 'Net' object has no attribute 'start_flops_count'.
Do you have any idea why I get this error and how can i solve it?

**Comment by sovrasov** [comment]
Hi! Please take a look to the pytorch guidelines for saving models: https://pytorch.org/docs/stable/notes/serialization.html#recommend-saving-models
