### ISSUE TITLE
input_res的格式是什么？

### ISSUE THREAD

**Issue by changshuangzhao** [sovrasov/flops-counter.pytorch#31]
flops, params = get_model_complexity_info(net, input_res=(3, 256, 512), input_constructor=prepare_input, as_strings=True, print_per_layer_stat=True)

input_res的格式是什么？channel，row，col?还是channel，col，row？

**Comment by sovrasov** [comment]
Pytorch uses the NCHW data layout and the `input res` parameter follows this practice. So in your terms the order is channel, row, col.

**Comment by puyiwen** [comment]
> Pytorch 使用 NCHW 数据布局，`input res`参数也遵循这种做法。所以用你的话来说，顺序是通道、行、列。

Hi, if my model input is dict, and the dict have many keys, how can I set the input_res? Can you tell me an example code? Thank you very much!
