### ISSUE TITLE
今天大半天都被这个flops_counter带偏了，不管做什么尝试，我的shufflenetv2和mobilenetv2的loss 始终降不下来，而acc 就和随机猜得的一样，请问这是什么问题？

### ISSUE THREAD

**Issue by yangyuke001** [sovrasov/flops-counter.pytorch#4]
今天大半天都被这个flops_counter带偏了，不管做什么尝试，我的shufflenetv2和mobilenetv2的loss 始终降不下来，而acc 就和随机猜得的一样，

**Comment by yangyuke001** [comment]
今天大半天都被这个flops_counter带偏了，不管做什么尝试，我的shufflenetv2和mobilenetv2的loss 始终降不下来，而acc 就和随机猜得的一样

**Comment by grib0ed0v** [comment]
@yangyuke001 this repository is intended for counting flops/parameters. So, it's more like utility rather than code for training.

**Comment by yangyuke001** [comment]
> @yangyuke001 this repository is intended for counting flops/parameters. So, it's more like utility rather than code for training.

I  got it ,thank you very much!

**Comment by grib0ed0v** [comment]
@yangyuke001 Cool! Then you can close the issue
