### ISSUE TITLE
the result of GMac is negative number

### ISSUE THREAD

**Issue by chenxiahan** [sovrasov/flops-counter.pytorch#41]
Hi, thanks for your tools. However, why did the result of GMac is negativae number when I calculate my own model? This is my code and output.

```
model =ResUNet(layers=[2,3,4,6,3])
macs, params = get_model_complexity_info(model,(1,256,256), as_strings=True, 
print_per_layer_stat=True,verbose=True)
print('{:<30} {:<8}'.format('Computational complexity: ', macs))
print('{:<30} {:<8}'.format('Number of parameters: ', params))
```
Computational complexity:      -52.1 GMac
Number of parameters:          97.23 M

**Comment by sovrasov** [comment]
Hi. Do you use pytorch on Windows ?

**Comment by chenxiahan** [comment]
> Hi. Do you use pytorch on Windows ?

Yes.

**Comment by sovrasov** [comment]
It's a well-known issue caused by specific of python interpreter on Windows. I see that pytorch on Windows becomes more popular, so I'm going to fix that.
Could you provide the details of your environment? (Windows version, CUDA version, pytorch version, python distribution type and version)

**Comment by chenxiahan** [comment]
windows 10 Professional
CUDA version: 9.0
pytorch version: 1.1.0
python 3.6.4
Thank you for your work.

**Comment by sovrasov** [comment]
Take a look at #43
