### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by kunjing96** [sovrasov/flops-counter.pytorch#47]
To get the number of FLOPs and params, use "get_model_complexity_info". But I get an Error, Illegal instruction (core dumped).

**Comment by sovrasov** [comment]
Hi! Could you please provide the code of your model to reproduce the issue?

**Comment by kunjing96** [comment]
A few days ago, it ran normally. And I run the same code on another machine. Then I got the error.
I found Pytorch == 1.1.0, torchvision == 0.2.0 on the another machine, which does meet the requirements(Pytorch >= 0.4.1, torchvision >= 0.2.1).  I think it works. Thanks!

**Comment by AlanZhang1995** [comment]
I am sorry, but I met the same problem.
I use the second command to install ptflops: `pip install --upgrade git+https://github.com/sovrasov/flops-counter.pytorch.git`
The codes are just the given example.
```python
import torchvision.models as models
import torch
from ptflops import get_model_complexity_info

with torch.cuda.device(0):
  net = models.densenet161()
  macs, params = get_model_complexity_info(net, (3, 224, 224), as_strings=True,
                                           print_per_layer_stat=True, verbose=True)
  print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
  print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```
And the error goes like this:
```
Warning: module _DenseLayer is treated as a zero-op.
Warning: module _DenseBlock is treated as a zero-op.
Warning: module _Transition is treated as a zero-op.
Warning: module DenseNet is treated as a zero-op.
Illegal instruction (core dumped)
```
