### ISSUE TITLE
FLOPS for LSTM model

### ISSUE THREAD

**Issue by preksha12** [sovrasov/flops-counter.pytorch#50]
How to compute FLOPS for LSTM model for skeleton data (NTU-RGBD)?  Error is due to input_res parameter as for skeleton data what should be this value.

**Comment by sovrasov** [comment]
Hi! I don't know what shape is exactly suitable for your model. If it has two inputs, you can arrange the inputs arguments in a custom way, like in #14.

**Comment by preksha12** [comment]
Actually I am trying to calculate FLOPS for NTU-RGBD dataset with skeleton data.
