### ISSUE TITLE
FLOPS for CIFAR10 or CIFAR100

### ISSUE THREAD

**Issue by miltonmondal** [sovrasov/flops-counter.pytorch#51]
Can anyone help me regarding how to use this code for 10 class (other than Imagenet) classification with our custom architechture ?

**Comment by sovrasov** [comment]
Take a look at the sample code in readme.md.
You have to create an instance of your model and then pass it to `get_model_complexity_info`. You have to also the input shape of your model (for CIFAR-10 it usually equals to (3, 32, 32)).

**Comment by miltonmondal** [comment]
Thanks a lot
