### ISSUE TITLE
print repr instead of str

### ISSUE THREAD

**Issue by 0phoff** [sovrasov/flops-counter.pytorch#55]
Hey, Thanks for your package it is quite useful!

I have one small issue and that is that the models I use have a ``__str__`` method defined on them, which prints a shorter version of the modules and thus the ``__repr__`` is not used. This causes your ``print_per_layer_stat`` argument not to work correctly.

In order to fix this, you could replace [Line 144](https://github.com/sovrasov/flops-counter.pytorch/blob/276d96d48e78113038ff645bc91d6cb969519a4c/ptflops/flops_counter.py#L144):
```python
print(repr(model), file=ost)
```

This will force to use the ``__repr__`` of the module, independent of whether a ``__str__`` has been defined or not.

**Comment by sovrasov** [comment]
Indeed, `extra_repr` appends some info to the result of `__repr__` and then the default `__str__` calls `__repr__`.
Thanks for the proposal. I'll push the changes to the master branch.
