### ISSUE TITLE
The flops calculation of ConvTranspose2d (Deconv)

### ISSUE THREAD

**Issue by Spark001** [sovrasov/flops-counter.pytorch#57]
The flops of ConvTranspose2d operation maybe not correct? 

It should be calculated as same as Conv2d: `K_w*K_h*C_in*C_out*O_w*O_h` when group = 1.

However your implement is `K_w*K_h*C_in*C_out*I_w*I_h` as follows:

https://github.com/sovrasov/flops-counter.pytorch/blob/b35716da617b57cb96944b113928d54b8b9ee9b6/ptflops/flops_counter.py#L297

**Comment by sovrasov** [comment]
Indeed, that's a bug. Thanks for figuring out, I'll fix it.

**Comment by sovrasov** [comment]
Resolved in #58
