### ISSUE TITLE
Counting bias addition ops for linear layers

### ISSUE THREAD

**Issue by vanyalzr** [sovrasov/flops-counter.pytorch#60]
Seems like you add bias addition ops to the total FLOPs count for convolutional and RNN modules, but it looks like it is not the case [for linear layers](https://github.com/sovrasov/flops-counter.pytorch/blob/015ad15ee44eb62c71da8fbe274aa1357fcb42e3/ptflops/flops_counter.py#L272). Is that something to be addressed?

**Comment by sovrasov** [comment]
Hi! That's a bug indeed. Thanks for catching it.
