### ISSUE TITLE
why i can not import get_model_complexity_info

### ISSUE THREAD

**Issue by sundongwei** [sovrasov/flops-counter.pytorch#63]
![image](https://user-images.githubusercontent.com/30918654/102305381-dcfcca80-3f9a-11eb-9792-beda872e3859.png)

**Comment by sovrasov** [comment]
This issue is related to your software environment. Please check that you're using the same python environment where you installed ptflops. See the installation instruction in readme.md in the root of this repository.

**Comment by sundongwei** [comment]
> This issue is related to your software environment. Please check that you're using the same python environment where you installed ptflops. See the installation instruction in readme.md in the root of this repository.

thank your for your reply.
