### ISSUE TITLE
Why is there no support for depthwise separable convolution？

### ISSUE THREAD

**Issue by TachibanaYoshino** [sovrasov/flops-counter.pytorch#7]
Lack of support for depthwise separable convolution

**Comment by sovrasov** [comment]
In pytorch depthwise separable convolutions are implemented via setting grouping in nn.Conv*. See https://discuss.pytorch.org/t/depthwise-and-separable-convolutions-in-pytorch/7315
ptflops supports the `groups` parameter, so it also supports depthwise convolutions.

**Comment by TachibanaYoshino** [comment]
Yes, I just remembered it. The depthwise convolution in the pytorch version of mobilenet V2 is implemented this way. Thank you so much!
