### ISSUE TITLE
Does it support torch.bmm() or torch.matmul()

### ISSUE THREAD

**Issue by kamiLight** [sovrasov/flops-counter.pytorch#78]
One part of my model performs the matrix multiplication, i.e torch.bmm() / torch.matmul(), but results show the GMac of this part is 0.0,  i want to know if this is because the GMac is too small or it is not support torch.bmm() or torch.matmul()？

**Comment by sovrasov** [comment]
ptflops can take into account only ops that derived from nn.Module. Support of  torch.bmm and similar operations requires complete redesign of the flops counting mechanism. I've started thinking of that but barely will do this soon.

**Comment by sovrasov** [comment]
Supported by both pytorch and aten backend, see https://github.com/sovrasov/flops-counter.pytorch/blob/master/ptflops/pytorch_ops.py#L443
