### ISSUE TITLE
Input of the model must be one?

### ISSUE THREAD

**Issue by Y1YU** [sovrasov/flops-counter.pytorch#93]
It seems that ptflops only work when the input of the model only be one. If my model has two inputs, one is (3, 224, 224), one is (17), then it will report an error.

**Comment by sovrasov** [comment]
Hi! See https://github.com/sovrasov/flops-counter.pytorch/issues/14

**Comment by Y1YU** [comment]
Thank you for your answer. And I want to ask if 1 GFLOPs == 2 GMacs？

**Comment by sovrasov** [comment]
This was discussed in #16
