### ISSUE TITLE
pytorch_ops of other activate functions are needed!

### ISSUE THREAD

**Issue by leyo42** [sovrasov/flops-counter.pytorch#97]
we can know that there are only relu activations in pytorch_ops.py，can you add other activations such as HSwish?

**Comment by leyo42** [comment]
Dear&nbsp;Sir or Madam:




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sovrasov/flops-counter.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sovrasov/flops-counter.pytorch] pytorch_ops of other activate functions are needed! (Issue #97)





 
Since it's hard to estimate the actual computation complexity of nonlinear activations, ptflops considers them as 1 flops op, see https://github.com/sovrasov/flops-counter.pytorch/blob/master/ptflops/pytorch_ops.py#L233-L237
 HSwish are not in the list, but can be easily added.

**Comment by leyo42** [comment]
Dear Sir or Madam:
Thanks for your reply！Can you tell me if this is the right change to calculate flops of HSwish？If not,please tell me correct answer,it is importmant for me,I will use in my experiment,thank you again！




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "sovrasov/flops-counter.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sovrasov/flops-counter.pytorch] pytorch_ops of other activate functions are needed! (Issue #97)





 
Since it's hard to estimate the actual computation complexity of nonlinear activations, ptflops considers them as 1 flops op, see https://github.com/sovrasov/flops-counter.pytorch/blob/master/ptflops/pytorch_ops.py#L233-L237
 HSwish are not in the list, but can be easily added.

**Comment by sovrasov** [comment]
You could add to the `MODULES_MAPPING`:
```python
nn.Hardswish: relu_flops_counter_hook,
```
